dist: trusty
language: go
go:
- "1.13"

install:
- make install

script:
- make test

before_deploy:
- make build

deploy:
  provider: releases
  api_key: "$GITHUB_API_KEY"
  skip_cleanup: true
  file_glob: true
  file: bin/*
  on:
    tags: true
